clear all
close all
clc

fs = 5000;

% read input
fIn = fopen('../dps/firFilter/data/input.pcm','r');
input = fread(fIn, inf, 'int16');
fclose(fIn);

% read output generated by the DSP board
fOut = fopen('../dps/firFilter/data/output.pcm','r');
boardOutput = fread(fOut, inf, 'int16');
fclose(fOut);

% matlab generated result
load('Num.mat');
filt = Num;
matlabOutput = filter(filt, 1, input);

numSamples = 200;
figure(1);
subplot(3, 1, 1); plot(input(1:numSamples));
title('Input signal');
subplot(3, 1, 2); plot(boardOutput(1:numSamples));
title('Singal filtered on board');
subplot(3, 1, 3); plot(matlabOutput(1:numSamples));
title('Signal filtered in matlab');

% Magnitude and phase analysis
H = fftshift(abs(fft(input)));
Hboard = fftshift(abs(fft(boardOutput)));
Hmatlab = fftshift(abs(fft(matlabOutput)));

Fboard = angle(fft(boardOutput));
Fmatlab = angle(fft(matlabOutput));

f = fs * (-length(input)/2:length(input)/2-1)/length(input);

figure(2);
subplot(3, 1, 1); plot(f, H);
title('Input maginitude plot');
xlabel('f[Hz]');
subplot(3, 1, 2); plot(f, Hboard);
title('Board output magnitude plot');
xlabel('f[Hz]');
subplot(3, 1, 3); plot(f, Hmatlab);
title('Matlab output magnitude plot');
xlabel('f[Hz]');

figure(3);
subplot(2, 1, 1); plot(f, Fboard);
title('Board output phase plot');
xlabel('f[Hz]');
subplot(2, 1, 2); plot(f, Fmatlab);
title('Matlab output phase plot');
xlabel('f[Hz]');



